name: Spread secrets to all repos

on:
    push:
        branches:
            - master

jobs:
    github-secret-spreader:
        name: Update secrets
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
            -   name: Checkout submodules
                shell: bash
                run: |
                    auth_header="$(git config --local --get http.https://github.com/.extraheader)"
                    git submodule sync --recursive
                    git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
            -   run: bin/spread
                env:
                    SPREAD_GITHUB_TOKEN: ${{ secrets.SPREAD_GITHUB_TOKEN }}
                    SPREAD_PRIVATE_KEY: ${{ secrets.SPREAD_PRIVATE_KEY }}
